# Generated by Django 4.1.5 on 2023-03-03 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_mumble_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mumble',
            name='image',
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('file', models.FileField(upload_to='MumbleVideo')),
                ('length', models.DecimalField(decimal_places=2, max_digits=100)),
                ('mumble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.mumble')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='MumbleImage')),
                ('mumble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.mumble')),
            ],
        ),
    ]
