# Generated by Django 4.1.5 on 2023-06-07 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_remove_mumble_image_video_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('file', models.FileField(upload_to='Mumblemedia')),
                ('length', models.DecimalField(decimal_places=2, max_digits=100)),
                ('mumble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.mumble')),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='mumble',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
